### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Victoria2333** [zhly0/facenet-face-cluster-chinese-whispers-#2]
Hello,I want to ask where the facenet module (import facenet)you used in the code was downloaded,is facenet the same as the pretrained model on https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw?
Thank you very much~

**Comment by zhly0** [comment]
yes，the facenet module in the code is from davidsanberg's facenet,all you need to do is put the code in the same place to facenet.py,the pretrained model  you can use the one from the url you memtioned if you have not trained one yourself

**Comment by Victoria2333** [comment]
Thanks for replying,I put your code in the folder containing facenet.py,and when i python facenet_face_cluster.py,there shows:
han@han:~/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/src$ python facenet_face_cluster.py
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
usage: facenet_face_cluster.py [-h] --model_dir MODEL_DIR --batch_size
                               BATCH_SIZE --input INPUT --output OUTPUT
facenet_face_cluster.py: error: argument --model_dir is required
So what parameters should i input,and do i need to train or test the facenet repository firstly or just run your code directly?I am not researching on this field...just working on something related.
Thanks ~~

**Comment by zhly0** [comment]
the code is write under python3,and the parameter is clear in the function:parse_args,so you need to run like this：python3 facenet_face_cluster.py --model_dir model --batch_size 30 --input image_dir --output output_image_dir

**Comment by Victoria2333** [comment]
Thanks for replying,I put your code in the folder containing facenet.py,and when i python facenet_face_cluster.py,there shows:
han@han:~/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/src$ python facenet_face_cluster.py
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
"This module will be removed in 0.20.", DeprecationWarning)
usage: facenet_face_cluster.py [-h] --model_dir MODEL_DIR --batch_size
BATCH_SIZE --input INPUT --output OUTPUT
facenet_face_cluster.py: error: argument --model_dir is required
So what parameters should i input,and do i need to train or test the facenet repository firstly or just run your code directly?I am not researching on this field...just working on some project related.
Thanks for your patience~~

**Comment by Victoria2333** [comment]
uh...my environment is python2.7,is it compatible with your code?
So running the former facenet is not required,haha~~
Thanks for your patience~~

**Comment by zhly0** [comment]
you could test it under python 2,I install python3,so I don't know if it can works under python 2,but it should be.
