### ISSUE TITLE
load_model() takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by Victoria2333** [zhly0/facenet-face-cluster-chinese-whispers-#3]
Hi,i execute:
python facenet_face_cluster.py --model_dir ./src/models/20170512-110547 --batch_size 30 --input ./datasets/lfw/lfw_mtcnnpy_160 --output output_img
and it ends like:
Traceback (most recent call last):
  File "facenet_face_cluster.py", line 270, in <module>
    main(parse_args())
  File "facenet_face_cluster.py", line 208, in main
    facenet.load_model(args.model_dir, meta_file, ckpt_file)
TypeError: load_model() takes exactly 1 argument (3 given)
And,I changed your code:
old:facenet.load_model(args.model_dir, meta_file, ckpt_file)
new:facenet.load_model(args.model_dir)
it still occurs the same problem...
Thanks very much for your help

**Comment by Victoria2333** [comment]
Another question: the input  should be facenet/lfw/lfw_mtcnnpy_160 or arbitrary folder containing pictures of many people?

**Comment by zhly0** [comment]
I update the py file,now,it will be ok,I use the facenet months ago,and now it has some update which i did not catch up.
Originally,I use this code to clean the training data,so,the input dir is like A,and in A,there are many dir containing every dir has many images need to cluster,if you just has one dir to cluster,you have to modify the code a little bit

**Comment by zhly0** [comment]
@Victoria2333 ,you can refer to this issue,it has someone use the code like you did:
https://github.com/davidsandberg/facenet/issues/370

**Comment by Victoria2333** [comment]
Thank you,i'll have a try~

**Comment by Victoria2333** [comment]
想问一下楼主有没有关于可以将视频中出现的人脸进行聚类成各个文件夹的程序,如果要对这个程序更改的话主要更改哪些部分?我是新手,不太理解这些算法...
Thanks~~

**Comment by Victoria2333** [comment]
想问一下楼主有没有关于可以将视频中出现的人脸进行聚类成各个文件夹的程序,就是比如我现在有input_img,里面还有一个all文件夹,再里面有A,B,C三个人,A有1张,B 有两张,C有三张,我想通过这个程序输出output_img,里面分成A,B,C三个文件夹,分别有1,2,3张图片.我根据davidsandberg/facenet#370里的提示
 put all images in "input_img/all/" folder, and set "input_img" folder as --input value.
change code like below in facenet_face_cluster.py
// cluster_dir = dest_dir
cluster_dir = dest_dir + "_" + str(idx)
but it only create one folder which has the most pictures of himself,others are ignored.

**Comment by Victoria2333** [comment]
For example,i execute:
python facenet_face_cluster.py --model_dir ./src/models/20170512-110547 --batch_size 30 --input input_img --output output_img
and i print sorted_clusters and num_cluster it occurs:
Runnning forward pass on images
1(counter)
[['input_img/all/Abdullah_0004.png', 'input_img/all/Abdullah_0003.png', 'input_img/all/Abdullah_0002.png', 'input_img/all/Abdullah_0001.png'], ['input_img/all/Abdullah_al-Attiyah_0003.png', 'input_img/all/Abdullah_al-Attiyah_0002.png', 'input_img/all/Abdullah_al-Attiyah_0001.png'], ['input_img/all/Abdoulaye_Wade_0002.png', 'input_img/all/Abdoulaye_Wade_0003.png', 'input_img/all/Abdoulaye_Wade_0001.png'], ['input_img/all/Abdel_Nasser_Assidi_0001.png', 'input_img/all/Abdel_Nasser_Assidi_0002.png']](sorted_clusters)
4(num_clusters)
Actually,there are other picture([Abdel_Madi_Shabneh_0001.png], [Abdullatif_Sener_0001.png,Abdullatif_Sener_0002.png])in input_img,it cannot be recognized,and it cannot create any folder in output_img,would you help me ? 
it only created one folder which has the most pictures of himself,others are ignored!!!

**Comment by zhly0** [comment]
uncomment 244,comment line 246,should do:
cluster_dir = join(dest_dir, str(idx))

#cluster_dir = dest_dir
#if len(cluster)<5:
#break

**Comment by Victoria2333** [comment]
I did exactly like your instruction yesterday,but it showed the resluts above...

**Comment by Victoria2333** [comment]
Could I get your contact and ask you some python questions if you are convenient~~~
If you are not willing to,it is also ok~~~~,i should learn from you guys on programming~~~haha

**Comment by zhly0** [comment]
you have to modify the code yourself,since I don't have much time to do it for you...
