### ISSUE TITLE
How to extract multiple faces in align_dataset_mtcnn.py ?

### ISSUE THREAD

**Issue by Victoria2333** [zhly0/facenet-face-cluster-chinese-whispers-#4]
I execute:
python src/align/align_dataset_mtcnn.py input output --image_size 160 --margin 32 --random_order
And there are multiple faces in one of those images,but the result only shows one face in each image,how can i modify this code?
Please give me some tips~~~

**Comment by zhly0** [comment]
@Victoria2333  you should ask facenet,
