### ISSUE TITLE
shuffle(cluster_nodes) result in errors

### ISSUE THREAD

**Issue by perfecthu** [zhly0/facenet-face-cluster-chinese-whispers-#5]
Here is the error message:
Traceback (most recent call last):
  File "src/facenet_face_cluster.py", line 258, in <module>
    main(parse_args())
  File "src/facenet_face_cluster.py", line 223, in main
    sorted_clusters = cluster_facial_encodings(facial_encodings)
  File "src/facenet_face_cluster.py", line 146, in cluster_facial_encodings
    sorted_clusters = _chinese_whispers(facial_encodings.items())
  File "src/facenet_face_cluster.py", line 86, in _chinese_whispers
    shuffle(cluster_nodes)
  File "/usr/lib/python2.7/random.py", line 289, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'NodeView' object does not support item assignment

Could you please provide some solutions?
The version of networkx (2.0)

**Comment by zhly0** [comment]
there may be two possible reasons ：
first，I use the code under python 3.4，not python 2.7，so I don‘t know if it works in python 2.7 or not 
second，the code was used for clean a face dataset，the face dataset has the following data directory structure，like directory a，in a you have many directory like 1，2，3，4。。。every directory in a represent a small image set which needs to cluster，if you have just one directory to cluster，you need to modify the code a little bit，good luck。

**Comment by perfecthu** [comment]
It seems that Shuffle cannot work on NodeView in  Python 2.7
